/* Definitions for driver AXI_ETHERNETLITE */
#define XPAR_AXI_ETHERNETLITE_BASEADDR 0X40E00000
#define XPAR_AXI_ETHERNETLITE_HIGHADDR 0X40E0FFFF 

/* Definitions for driver AXI_GPIO */
#define XPAR_AXI_GPIO_BASEADDR 0X40000000
#define XPAR_AXI_GPIO_HIGHADDR 0X4000FFFF 

/* Definitions for driver AXI_UARTLITE */
#define XPAR_AXI_UARTLITE_BASEADDR 0X40600000
#define XPAR_AXI_UARTLITE_HIGHADDR 0X4060FFFF 

/* Definitions for driver CLK_WIZ_1 */
#define XPAR_CLK_WIZ_1_BASEADDR 
#define XPAR_CLK_WIZ_1_HIGHADDR  

/* Definitions for driver DDR_RSTGEN */
#define XPAR_DDR_RSTGEN_BASEADDR 
#define XPAR_DDR_RSTGEN_HIGHADDR  

/* Definitions for driver INST_RUFFLE_AXI_BSCANE */
#define XPAR_INST_RUFFLE_AXI_BSCANE_BASEADDR 0X00400000
#define XPAR_INST_RUFFLE_AXI_BSCANE_HIGHADDR 0X007FFFFF 

/* Definitions for driver IRQ_CONCAT */
#define XPAR_IRQ_CONCAT_BASEADDR 
#define XPAR_IRQ_CONCAT_HIGHADDR  

/* Definitions for driver SYS_RSTGEN */
#define XPAR_SYS_RSTGEN_BASEADDR 
#define XPAR_SYS_RSTGEN_HIGHADDR  

/* Definitions for driver XLCONSTANT_0 */
#define XPAR_XLCONSTANT_0_BASEADDR 
#define XPAR_XLCONSTANT_0_HIGHADDR  

